# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Test, and Build Storybook
    runs-on: ubuntu-20.04
    steps:

      - name: Download Zephyr release
        run: curl -Ls https://github.com/coot/zephyr/releases/download/v0.3.2/Linux.tar.gz | tar -xvz -C /tmp
      - name: Copy Zephyr to PATH
        run: sudo cp /tmp/zephyr/zephyr /usr/local/bin/

      - name: Install yarn
        run: sudo npm install -g yarn

      # Run actual tasks
      - uses: actions/checkout@v2
      ## Frontend
      - name: Install Frontend Dependencies
        run: yarn install
      - name: Test Frontend
        run: yarn test
      - name: Build Storybook
        run: yarn build-storybook
